apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/mohammad-ammar14/ocm-food-app
  provider:
    name: mohammad-ammar14
  version: 1.0.0-dev
repositoryContexts: []
spec:
  references:
  - componentName: github.com/mohammad-ammar14/carts
    name: carts
    version: 1.0.0

# apiVersion: ocm.software/v3alpha1
# kind: ComponentVersion
# metadata:
#   name: nested-component
#   namespace: default
# spec:
#   interval: 1m0s
#   component: github.com/mohammad-ammar14/ocm-food-app
#   version:
#     semver: ">=v1.0.0"
#   repository:
#     url: ghcr.io/mohammad-ammar14
#     secretRef:
#       name: creds
#   references:
#     expand: true