# apiVersion: delivery.ocm.software/v1alpha1
# kind: ComponentVersion
# metadata:
#   name: ocm-food-app
#   namespace: default
#   provider:
#     name: mohammad-ammar14
#   version: 1.0.0-dev
# repositoryContexts: []
# spec:
#   references:
#   - componentName: github.com/mohammad-ammar14/carts
#     name: carts
#     version: 1.0.0

apiVersion: delivery.ocm.software/v1alp
kind: ComponentVersion
metadata:
  name: ocm-food-app
  namespace: default
  provider: 
    name: mohammad-ammar14
  version: 1.0.0  
spec:
  interval: 1m0s
  component: github.com/mohammad-ammar14/ocm-food-app
  version:
    semver: ">=v1.0.0"
  repository:
    url: ghcr.io/mohammad-ammar14
    secretRef:
      name: creds
  references:
  - componentName: github.com/mohammad-ammar14/carts
    name: carts
    version: 1.0.0
    